# 代码生成器配置
generator:
  # 后端项目名称
  backendAppName: youlai-boot
  # 前端项目名称
  frontendAppName: vue3-element-admin
  # 默认配置
  defaultConfig:
    author: youlaitech
  # 排除数据表
  excludeTables:
    - gen_config
    - gen_field_config
  ## 模板配置
  templateConfigs:
    Controller:
      templatePath: generator/controller.java.vm
      packageName: controller
    Service:
      templatePath: generator/service.java.vm
      packageName: service
    ServiceImpl:
      templatePath: generator/serviceImpl.java.vm
      packageName: service.impl
    Mapper:
      templatePath: generator/mapper.java.vm
      packageName: mapper
    MapperXml:
      templatePath: generator/mapper.xml.vm
      packageName: mapper
      extension: .xml
    Converter:
      templatePath: generator/converter.java.vm
      packageName: converter
    Query:
      templatePath: generator/query.java.vm
      packageName: model.query
    Form:
      templatePath: generator/form.java.vm
      packageName: model.form
    VO:
      templatePath: generator/vo.java.vm
      packageName: model.vo
    Entity:
      templatePath: generator/entity.java.vm
      packageName: model.entity
    API:
      templatePath: generator/api.ts.vm
      packageName: api
      extension: .ts
    VIEW:
      templatePath: generator/index.vue.vm
      packageName: views
      extension: .vue



