name: Deploy Java Maven Project
on:
  push:
    branches:
      - master  # 更改为你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17          
          distribution: 'adopt'
          cache: 'maven'
      - name: maven package
        run: mvn clean  package
